title: Javascript Planet
author: siegblink
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is all about the world of Javascript and everything about modern web development.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
